### PR TITLE
removes dependency on localgov_workflows

### LINKED ISSUE #5: Config has a dependency on localgov_workflows which isn't a module dependency (might not be enabled)
Whilst debugging the issue raised in #1 when ordering the installation so that this module is enabled before localgov_workflows I go this error.

> Configuration objects provided by <em class="placeholder">localgov_job_vacancies</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.node.localgov_job_vacancy.default (workflows.workflow.localgov_editorial)</em>

This is becuase there is a dependency in config in the above file. I belive modules should be able to work without localgov_workflows installed so we should fix that. Localgov_workflows will add the appropriate content moderation to each content type once it is enabled.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #5 

## What does this change?

Removes dependency on `localgov_workflows` module.

## How to test

Install the module without already having LocalGov Workflows module installed.

## How can we measure success?
The module installs without error.

### CODE REVIEW

**Review by ctorgalson — APPROVED** [review]
WFM. So should this close #1? There's no current *functional* need for the module to ship workflow/scheduled transition things, but I don't know what LGD's expectations are in this regard for new modules.

**Comment by markconroy** [comment]
Yes, let's merge this so it works, close/fix #1 and then decide later if we want this to have a dependency on workflows module.

Does that sound sound?

**Comment by andybroomfield** [comment]
@ctorgalson For #1 the issue is that is should set up scheduled transition permissions, if scheduled transitions is installed, though the question I have on localgov_workflows is which module should take responsibilty (if at all, we could say it's up to the user to do so!)

**Comment by markconroy** [comment]
@andybroomfield are you okay for us to merge this issue and figure that out as a follow-up?

**Comment by andybroomfield** [comment]
Yes thats fine.

**Pull request merged**
